// Mocks generated by Mockito 5.4.4 from annotations
// in capest_timeline/test/unit/services/capacity_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:capest_timeline/models/models.dart' as _i5;
import 'package:capest_timeline/services/storage_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  @override
  _i2.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
        returnValueForMissingStub: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i2.SharedPreferences);

  @override
  _i4.Future<void> saveKanbanState(Map<String, dynamic>? kanbanState) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKanbanState,
          [kanbanState],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> loadKanbanState() => (super.noSuchMethod(
        Invocation.method(
          #loadKanbanState,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> saveInitiative(_i5.Initiative? initiative) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveInitiative,
          [initiative],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Initiative>> loadInitiatives() => (super.noSuchMethod(
        Invocation.method(
          #loadInitiatives,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Initiative>>.value(<_i5.Initiative>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Initiative>>.value(<_i5.Initiative>[]),
      ) as _i4.Future<List<_i5.Initiative>>);

  @override
  _i4.Future<void> savePlatformVariant(_i5.PlatformVariant? variant) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePlatformVariant,
          [variant],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.PlatformVariant>> loadPlatformVariants() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPlatformVariants,
          [],
        ),
        returnValue: _i4.Future<List<_i5.PlatformVariant>>.value(
            <_i5.PlatformVariant>[]),
        returnValueForMissingStub: _i4.Future<List<_i5.PlatformVariant>>.value(
            <_i5.PlatformVariant>[]),
      ) as _i4.Future<List<_i5.PlatformVariant>>);

  @override
  _i4.Future<void> saveTeamMember(_i5.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTeamMember,
          [member],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TeamMember>> loadTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #loadTeamMembers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i4.Future<List<_i5.TeamMember>>);

  @override
  _i4.Future<void> saveAssignment(_i5.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAssignment,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Assignment>> loadAssignments() => (super.noSuchMethod(
        Invocation.method(
          #loadAssignments,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Assignment>>.value(<_i5.Assignment>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Assignment>>.value(<_i5.Assignment>[]),
      ) as _i4.Future<List<_i5.Assignment>>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<DateTime?> getLastUpdated() => (super.noSuchMethod(
        Invocation.method(
          #getLastUpdated,
          [],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
        returnValueForMissingStub: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);
}
