// Mocks generated by Mockito 5.4.4 from annotations
// in capest_timeline/test/unit/services/kanban_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:capest_timeline/models/models.dart' as _i5;
import 'package:capest_timeline/services/capacity_service.dart' as _i6;
import 'package:capest_timeline/services/storage_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageService_1 extends _i1.SmartFake
    implements _i3.StorageService {
  _FakeStorageService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  @override
  _i2.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
        returnValueForMissingStub: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i2.SharedPreferences);

  @override
  _i4.Future<void> saveKanbanState(Map<String, dynamic>? kanbanState) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKanbanState,
          [kanbanState],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> loadKanbanState() => (super.noSuchMethod(
        Invocation.method(
          #loadKanbanState,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> saveInitiative(_i5.Initiative? initiative) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveInitiative,
          [initiative],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Initiative>> loadInitiatives() => (super.noSuchMethod(
        Invocation.method(
          #loadInitiatives,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Initiative>>.value(<_i5.Initiative>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Initiative>>.value(<_i5.Initiative>[]),
      ) as _i4.Future<List<_i5.Initiative>>);

  @override
  _i4.Future<void> savePlatformVariant(_i5.PlatformVariant? variant) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePlatformVariant,
          [variant],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.PlatformVariant>> loadPlatformVariants() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPlatformVariants,
          [],
        ),
        returnValue: _i4.Future<List<_i5.PlatformVariant>>.value(
            <_i5.PlatformVariant>[]),
        returnValueForMissingStub: _i4.Future<List<_i5.PlatformVariant>>.value(
            <_i5.PlatformVariant>[]),
      ) as _i4.Future<List<_i5.PlatformVariant>>);

  @override
  _i4.Future<void> saveTeamMember(_i5.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTeamMember,
          [member],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TeamMember>> loadTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #loadTeamMembers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i4.Future<List<_i5.TeamMember>>);

  @override
  _i4.Future<void> saveAssignment(_i5.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAssignment,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Assignment>> loadAssignments() => (super.noSuchMethod(
        Invocation.method(
          #loadAssignments,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Assignment>>.value(<_i5.Assignment>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Assignment>>.value(<_i5.Assignment>[]),
      ) as _i4.Future<List<_i5.Assignment>>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<DateTime?> getLastUpdated() => (super.noSuchMethod(
        Invocation.method(
          #getLastUpdated,
          [],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
        returnValueForMissingStub: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);
}

/// A class which mocks [CapacityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCapacityService extends _i1.Mock implements _i6.CapacityService {
  @override
  _i3.StorageService get storageService => (super.noSuchMethod(
        Invocation.getter(#storageService),
        returnValue: _FakeStorageService_1(
          this,
          Invocation.getter(#storageService),
        ),
        returnValueForMissingStub: _FakeStorageService_1(
          this,
          Invocation.getter(#storageService),
        ),
      ) as _i3.StorageService);

  @override
  _i4.Future<List<_i5.CapacityData>> calculateTeamCapacity({
    required DateTime? startDate,
    required DateTime? endDate,
    String? platformFilter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateTeamCapacity,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #platformFilter: platformFilter,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.CapacityData>>.value(<_i5.CapacityData>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.CapacityData>>.value(<_i5.CapacityData>[]),
      ) as _i4.Future<List<_i5.CapacityData>>);

  @override
  _i4.Future<List<_i5.CapacityPeriod>> getCapacityPeriods(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCapacityPeriods,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i4.Future<List<_i5.CapacityPeriod>>.value(<_i5.CapacityPeriod>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.CapacityPeriod>>.value(<_i5.CapacityPeriod>[]),
      ) as _i4.Future<List<_i5.CapacityPeriod>>);

  @override
  _i4.Future<List<String>> detectConflicts({
    required DateTime? startDate,
    required DateTime? endDate,
    String? platformFilter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectConflicts,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #platformFilter: platformFilter,
          },
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<Map<String, double>> calculateUtilization({
    required DateTime? startDate,
    required DateTime? endDate,
    String? roleFilter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateUtilization,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #roleFilter: roleFilter,
          },
        ),
        returnValue: _i4.Future<Map<String, double>>.value(<String, double>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> suggestAllocation({
    required _i5.Initiative? initiative,
    required DateTime? preferredStartDate,
    DateTime? deadline,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestAllocation,
          [],
          {
            #initiative: initiative,
            #preferredStartDate: preferredStartDate,
            #deadline: deadline,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> getMemberAvailability({
    required String? memberId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemberAvailability,
          [],
          {
            #memberId: memberId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getCapacityUtilization(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCapacityUtilization,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> validateCapacityConstraints(
          List<_i5.Assignment>? proposedAssignments) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateCapacityConstraints,
          [proposedAssignments],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
