// Mocks generated by Mockito 5.4.4 from annotations
// in capest_timeline/test/widget/week_column_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:capest_timeline/models/models.dart' as _i3;
import 'package:capest_timeline/providers/kanban_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [KanbanProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanbanProvider extends _i1.Mock implements _i2.KanbanProvider {
  @override
  List<_i3.Initiative> get initiatives => (super.noSuchMethod(
        Invocation.getter(#initiatives),
        returnValue: <_i3.Initiative>[],
        returnValueForMissingStub: <_i3.Initiative>[],
      ) as List<_i3.Initiative>);

  @override
  List<_i3.PlatformVariant> get platformVariants => (super.noSuchMethod(
        Invocation.getter(#platformVariants),
        returnValue: <_i3.PlatformVariant>[],
        returnValueForMissingStub: <_i3.PlatformVariant>[],
      ) as List<_i3.PlatformVariant>);

  @override
  List<DateTime> get timelineWeeks => (super.noSuchMethod(
        Invocation.getter(#timelineWeeks),
        returnValue: <DateTime>[],
        returnValueForMissingStub: <DateTime>[],
      ) as List<DateTime>);

  @override
  List<_i3.CapacityPeriod> get capacityPeriods => (super.noSuchMethod(
        Invocation.getter(#capacityPeriods),
        returnValue: <_i3.CapacityPeriod>[],
        returnValueForMissingStub: <_i3.CapacityPeriod>[],
      ) as List<_i3.CapacityPeriod>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> moveVariantToWeek(
    String? variantId,
    DateTime? targetWeek,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveVariantToWeek,
          [
            variantId,
            targetWeek,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> createInitiative(_i3.Initiative? initiative) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInitiative,
          [initiative],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateInitiative(_i3.Initiative? initiative) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInitiative,
          [initiative],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteInitiative(String? initiativeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteInitiative,
          [initiativeId],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  List<_i3.PlatformVariant> getVariantsForInitiative(String? initiativeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVariantsForInitiative,
          [initiativeId],
        ),
        returnValue: <_i3.PlatformVariant>[],
        returnValueForMissingStub: <_i3.PlatformVariant>[],
      ) as List<_i3.PlatformVariant>);

  @override
  List<_i3.PlatformVariant> getVariantsForWeek(DateTime? week) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVariantsForWeek,
          [week],
        ),
        returnValue: <_i3.PlatformVariant>[],
        returnValueForMissingStub: <_i3.PlatformVariant>[],
      ) as List<_i3.PlatformVariant>);

  @override
  _i3.CapacityPeriod? getCapacityForWeek(DateTime? week) => (super.noSuchMethod(
        Invocation.method(
          #getCapacityForWeek,
          [week],
        ),
        returnValueForMissingStub: null,
      ) as _i3.CapacityPeriod?);

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> retry() => (super.noSuchMethod(
        Invocation.method(
          #retry,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
