// Mocks generated by Mockito 5.4.4 from annotations
// in capest_timeline/test/unit/providers/kanban_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:capest_timeline/models/models.dart' as _i5;
import 'package:capest_timeline/services/capacity_service.dart' as _i3;
import 'package:capest_timeline/services/kanban_service.dart' as _i4;
import 'package:capest_timeline/services/storage_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStorageService_0 extends _i1.SmartFake
    implements _i2.StorageService {
  _FakeStorageService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCapacityService_1 extends _i1.SmartFake
    implements _i3.CapacityService {
  _FakeCapacityService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKanbanDataResult_2 extends _i1.SmartFake
    implements _i4.KanbanDataResult {
  _FakeKanbanDataResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInitiative_3 extends _i1.SmartFake implements _i5.Initiative {
  _FakeInitiative_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_4 extends _i1.SmartFake
    implements _i6.SharedPreferences {
  _FakeSharedPreferences_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KanbanService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanbanService extends _i1.Mock implements _i4.KanbanService {
  @override
  _i2.StorageService get storageService => (super.noSuchMethod(
        Invocation.getter(#storageService),
        returnValue: _FakeStorageService_0(
          this,
          Invocation.getter(#storageService),
        ),
        returnValueForMissingStub: _FakeStorageService_0(
          this,
          Invocation.getter(#storageService),
        ),
      ) as _i2.StorageService);

  @override
  _i3.CapacityService get capacityService => (super.noSuchMethod(
        Invocation.getter(#capacityService),
        returnValue: _FakeCapacityService_1(
          this,
          Invocation.getter(#capacityService),
        ),
        returnValueForMissingStub: _FakeCapacityService_1(
          this,
          Invocation.getter(#capacityService),
        ),
      ) as _i3.CapacityService);

  @override
  _i7.Future<_i4.KanbanDataResult> getKanbanData({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKanbanData,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i7.Future<_i4.KanbanDataResult>.value(_FakeKanbanDataResult_2(
          this,
          Invocation.method(
            #getKanbanData,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i4.KanbanDataResult>.value(_FakeKanbanDataResult_2(
          this,
          Invocation.method(
            #getKanbanData,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i7.Future<_i4.KanbanDataResult>);

  @override
  _i7.Future<_i5.Initiative> createInitiative(
          Map<String, dynamic>? initiativeData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInitiative,
          [initiativeData],
        ),
        returnValue: _i7.Future<_i5.Initiative>.value(_FakeInitiative_3(
          this,
          Invocation.method(
            #createInitiative,
            [initiativeData],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.Initiative>.value(_FakeInitiative_3(
          this,
          Invocation.method(
            #createInitiative,
            [initiativeData],
          ),
        )),
      ) as _i7.Future<_i5.Initiative>);

  @override
  _i7.Future<void> moveInitiative({
    required String? initiativeId,
    required DateTime? targetWeek,
    String? platformType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveInitiative,
          [],
          {
            #initiativeId: initiativeId,
            #targetWeek: targetWeek,
            #platformType: platformType,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> moveVariantToWeek(
    _i5.PlatformVariant? variant,
    DateTime? targetWeek,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveVariantToWeek,
          [
            variant,
            targetWeek,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateInitiative({
    required String? initiativeId,
    String? title,
    String? description,
    DateTime? dueDate,
    int? priority,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInitiative,
          [],
          {
            #initiativeId: initiativeId,
            #title: title,
            #description: description,
            #dueDate: dueDate,
            #priority: priority,
            #tags: tags,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteInitiative(String? initiativeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteInitiative,
          [initiativeId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> assignMember({
    required String? initiativeId,
    required String? memberId,
    required String? platformType,
    required double? capacityPercentage,
    required DateTime? startWeek,
    double? durationWeeks,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignMember,
          [],
          {
            #initiativeId: initiativeId,
            #memberId: memberId,
            #platformType: platformType,
            #capacityPercentage: capacityPercentage,
            #startWeek: startWeek,
            #durationWeeks: durationWeeks,
          },
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #assignMember,
            [],
            {
              #initiativeId: initiativeId,
              #memberId: memberId,
              #platformType: platformType,
              #capacityPercentage: capacityPercentage,
              #startWeek: startWeek,
              #durationWeeks: durationWeeks,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #assignMember,
            [],
            {
              #initiativeId: initiativeId,
              #memberId: memberId,
              #platformType: platformType,
              #capacityPercentage: capacityPercentage,
              #startWeek: startWeek,
              #durationWeeks: durationWeeks,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> unassignMember({required String? assignmentId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unassignMember,
          [],
          {#assignmentId: assignmentId},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [CapacityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCapacityService extends _i1.Mock implements _i3.CapacityService {
  @override
  _i2.StorageService get storageService => (super.noSuchMethod(
        Invocation.getter(#storageService),
        returnValue: _FakeStorageService_0(
          this,
          Invocation.getter(#storageService),
        ),
        returnValueForMissingStub: _FakeStorageService_0(
          this,
          Invocation.getter(#storageService),
        ),
      ) as _i2.StorageService);

  @override
  _i7.Future<List<_i5.CapacityData>> calculateTeamCapacity({
    required DateTime? startDate,
    required DateTime? endDate,
    String? platformFilter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateTeamCapacity,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #platformFilter: platformFilter,
          },
        ),
        returnValue:
            _i7.Future<List<_i5.CapacityData>>.value(<_i5.CapacityData>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.CapacityData>>.value(<_i5.CapacityData>[]),
      ) as _i7.Future<List<_i5.CapacityData>>);

  @override
  _i7.Future<List<_i5.CapacityPeriod>> getCapacityPeriods(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCapacityPeriods,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i7.Future<List<_i5.CapacityPeriod>>.value(<_i5.CapacityPeriod>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.CapacityPeriod>>.value(<_i5.CapacityPeriod>[]),
      ) as _i7.Future<List<_i5.CapacityPeriod>>);

  @override
  _i7.Future<List<String>> detectConflicts({
    required DateTime? startDate,
    required DateTime? endDate,
    String? platformFilter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectConflicts,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #platformFilter: platformFilter,
          },
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<Map<String, double>> calculateUtilization({
    required DateTime? startDate,
    required DateTime? endDate,
    String? roleFilter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateUtilization,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #roleFilter: roleFilter,
          },
        ),
        returnValue: _i7.Future<Map<String, double>>.value(<String, double>{}),
        returnValueForMissingStub:
            _i7.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i7.Future<Map<String, double>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> suggestAllocation({
    required _i5.Initiative? initiative,
    required DateTime? preferredStartDate,
    DateTime? deadline,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestAllocation,
          [],
          {
            #initiative: initiative,
            #preferredStartDate: preferredStartDate,
            #deadline: deadline,
          },
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<Map<String, dynamic>> getMemberAvailability({
    required String? memberId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemberAvailability,
          [],
          {
            #memberId: memberId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getCapacityUtilization(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCapacityUtilization,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> validateCapacityConstraints(
          List<_i5.Assignment>? proposedAssignments) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateCapacityConstraints,
          [proposedAssignments],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  @override
  _i6.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_4(
          this,
          Invocation.getter(#sharedPreferences),
        ),
        returnValueForMissingStub: _FakeSharedPreferences_4(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i6.SharedPreferences);

  @override
  _i7.Future<void> saveKanbanState(Map<String, dynamic>? kanbanState) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKanbanState,
          [kanbanState],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> loadKanbanState() => (super.noSuchMethod(
        Invocation.method(
          #loadKanbanState,
          [],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> saveInitiative(_i5.Initiative? initiative) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveInitiative,
          [initiative],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.Initiative>> loadInitiatives() => (super.noSuchMethod(
        Invocation.method(
          #loadInitiatives,
          [],
        ),
        returnValue: _i7.Future<List<_i5.Initiative>>.value(<_i5.Initiative>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.Initiative>>.value(<_i5.Initiative>[]),
      ) as _i7.Future<List<_i5.Initiative>>);

  @override
  _i7.Future<void> savePlatformVariant(_i5.PlatformVariant? variant) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePlatformVariant,
          [variant],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.PlatformVariant>> loadPlatformVariants() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPlatformVariants,
          [],
        ),
        returnValue: _i7.Future<List<_i5.PlatformVariant>>.value(
            <_i5.PlatformVariant>[]),
        returnValueForMissingStub: _i7.Future<List<_i5.PlatformVariant>>.value(
            <_i5.PlatformVariant>[]),
      ) as _i7.Future<List<_i5.PlatformVariant>>);

  @override
  _i7.Future<void> saveTeamMember(_i5.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTeamMember,
          [member],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.TeamMember>> loadTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #loadTeamMembers,
          [],
        ),
        returnValue: _i7.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i7.Future<List<_i5.TeamMember>>);

  @override
  _i7.Future<void> saveAssignment(_i5.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAssignment,
          [assignment],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.Assignment>> loadAssignments() => (super.noSuchMethod(
        Invocation.method(
          #loadAssignments,
          [],
        ),
        returnValue: _i7.Future<List<_i5.Assignment>>.value(<_i5.Assignment>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.Assignment>>.value(<_i5.Assignment>[]),
      ) as _i7.Future<List<_i5.Assignment>>);

  @override
  _i7.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<DateTime?> getLastUpdated() => (super.noSuchMethod(
        Invocation.method(
          #getLastUpdated,
          [],
        ),
        returnValue: _i7.Future<DateTime?>.value(),
        returnValueForMissingStub: _i7.Future<DateTime?>.value(),
      ) as _i7.Future<DateTime?>);
}
